//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePratico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADASTRO_CLIENTES
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string CPF { get; set; }
        public string EMISSOR { get; set; }
        public string UF_RG { get; set; }
        public System.DateTime DATA_NASC { get; set; }
        public string NATURALIDADE { get; set; }
        public string UF { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string NOME_PAI { get; set; }
        public string NOME_MAE { get; set; }
        public string ENDERECO_RESDEN { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string ESTADO { get; set; }
        public string TEL_CEL { get; set; }
        public string TEL_RESIDEN { get; set; }
    }
}
